/* Build 005 multi-domain UI integration.
 * Loaded after the Build 002/003/004 overlays. The light theme remains the final CSS layer.
 */
const DOMAIN_PAGE_SIZE = 100;
state.procQuery=''; state.procEntity='all'; state.procYear='all'; state.procPage=1;
state.capitalQuery=''; state.capitalYear='all'; state.capitalSource='all'; state.capitalPage=1;
state.spendQuery=''; state.spendType='all'; state.spendPeriod='all'; state.spendPage=1;

function domainRows(name){ return getRows(datasetStatus(name).data); }
function domainYear(value){ return value ? String(value).slice(0,4) : ''; }
function domainPagination(total,page,target){
  const pages=Math.max(1,Math.ceil(total/DOMAIN_PAGE_SIZE)); const current=Math.min(Math.max(1,page),pages);
  const start=total?(current-1)*DOMAIN_PAGE_SIZE+1:0, end=Math.min(current*DOMAIN_PAGE_SIZE,total);
  return `<div class="pagination domain-pagination"><span class="pagination-info">${numberFmt.format(start)}–${numberFmt.format(end)} of ${numberFmt.format(total)} · page ${current}/${pages}</span><div><button type="button" class="button subtle" data-domain-page="${target}" data-domain-step="-1" ${current<=1?'disabled':''}>Previous</button><button type="button" class="button subtle" data-domain-page="${target}" data-domain-step="1" ${current>=pages?'disabled':''}>Next</button></div></div>`;
}
function domainSlice(rows,page){ const pages=Math.max(1,Math.ceil(rows.length/DOMAIN_PAGE_SIZE)); const current=Math.min(Math.max(1,page),pages); return {current,rows:rows.slice((current-1)*DOMAIN_PAGE_SIZE,current*DOMAIN_PAGE_SIZE)}; }
function optionList(values,selected,allLabel){ return `<option value="all">${allLabel}</option>${values.map(value=>`<option value="${escapeHtml(value)}" ${value===selected?'selected':''}>${escapeHtml(value)}</option>`).join('')}`; }
function domainSource(row){ return sourceById(row.source_id); }
function domainNotice(title,text){ return `<div class="notice"><strong>${escapeHtml(title)}</strong><span>${escapeHtml(text)}</span></div>`; }

const build004Render=render;
render=function renderWithDomains(){
  build004Render();
  const filterbar=$('.filterbar');
  if(filterbar) filterbar.hidden=['budget','spending','procurement','capital'].includes(state.view);
};

renderProcurement=function renderProcurementIntegrated(){
  const ds=datasetStatus('procurement'); if(ds.status!=='ready') return domainUnavailable('procurement','Vendors & Contracts');
  const all=domainRows('procurement');
  const entities=[...new Set(all.map(r=>r.entity).filter(Boolean))].sort();
  const years=[...new Set(all.map(r=>domainYear(r.awarded_date)).filter(Boolean))].sort().reverse();
  const filtered=all.filter(r=>(state.procEntity==='all'||r.entity===state.procEntity)&&(state.procYear==='all'||domainYear(r.awarded_date)===state.procYear)&&(!state.procQuery||normalize(`${r.vendor_name||''} ${r.award_id||''} ${r.description||''} ${r.category||''} ${r.entity||''}`).includes(normalize(state.procQuery))));
  filtered.sort((a,b)=>String(b.awarded_date||'').localeCompare(String(a.awarded_date||''))||Number(b.original_award_value||0)-Number(a.original_award_value||0));
  const total=filtered.reduce((sum,r)=>sum+Number(r.original_award_value||0),0); const vendors=new Set(filtered.map(r=>normalize(r.vendor_name)).filter(Boolean)).size;
  const page=domainSlice(filtered,state.procPage); state.procPage=page.current;
  const table=page.rows.length?`<div class="table-wrap"><table><thead><tr><th>Award date</th><th>Vendor</th><th>Entity</th><th>Tender</th><th>Category</th><th class="numeric">Award value</th></tr></thead><tbody>${page.rows.map((r,i)=>`<tr data-proc-key="${escapeHtml(`${r.source_id||''}||${r.award_id||''}||${r.vendor_name||''}||${r.awarded_date||''}`)}"><td>${escapeHtml(String(r.awarded_date||'—').slice(0,10))}</td><td><strong>${escapeHtml(r.vendor_name||'—')}</strong></td><td>${escapeHtml(r.entity||'—')}</td><td>${escapeHtml(r.award_id||r.solicitation||'—')}</td><td>${escapeHtml(r.category||'—')}</td><td class="numeric"><strong>${money(r.original_award_value)}</strong></td></tr>`).join('')}</tbody></table></div>`:emptyState('No matching public-tender awards','Change the local procurement filters or search.');
  return `<div class="page-stack">${domainNotice('Coverage boundary','These are official public-tender award records, not an accounts-payable ledger and not a complete record of alternative procurements or later amendments.')}<div class="metrics-grid">${metricCard('Matching awards',numberFmt.format(filtered.length),'Official public-tender award rows','accent')}${metricCard('Award value',compactMoney(total),'Sum of matching published award values','neutral')}${metricCard('Vendors represented',numberFmt.format(vendors),'Raw published vendor names; not fuzzy-merged','neutral')}${metricCard('Reporting entities',numberFmt.format(new Set(filtered.map(r=>r.entity)).size),'Under current local filters','neutral')}</div>${panel('Public tender award explorer','Search and filter the provincial awarded-tenders collection. Click a row for source evidence.',`<div class="local-toolbar"><label class="local-search"><span>⌕</span><input id="proc-search" value="${escapeHtml(state.procQuery)}" placeholder="Search vendor, tender or description" /></label><select id="proc-entity">${optionList(entities,state.procEntity,'All reporting entities')}</select><select id="proc-year">${optionList(years,state.procYear,'All award years')}</select></div>${domainPagination(filtered.length,state.procPage,'proc')}${table}${domainPagination(filtered.length,state.procPage,'proc')}`)}</div>`;
};

renderCapital=function renderCapitalIntegrated(){
  const ds=datasetStatus('capital'); if(ds.status!=='ready') return domainUnavailable('capital','Capital Projects');
  const all=domainRows('capital');
  const years=[...new Set(all.map(r=>String(r.fiscal_year??r.budget_year??'')).filter(Boolean))].sort().reverse();
  const sources=[...new Set(all.map(r=>r.source_id).filter(Boolean))].sort();
  const filtered=all.filter(r=>(state.capitalYear==='all'||String(r.fiscal_year??r.budget_year??'')===state.capitalYear)&&(state.capitalSource==='all'||r.source_id===state.capitalSource)&&(!state.capitalQuery||normalize(`${r.project_code||''} ${r.project_name||''} ${r.location_description||''} ${r.work_description||''} ${r.category||''}`).includes(normalize(state.capitalQuery))));
  const projects=new Set(filtered.map(r=>r.project_id||r.project_code||r.project_name).filter(Boolean)).size;
  const page=domainSlice(filtered,state.capitalPage); state.capitalPage=page.current;
  const table=page.rows.length?`<div class="table-wrap"><table><thead><tr><th>Year</th><th>Project</th><th>Category</th><th>Location</th><th>Status / source</th></tr></thead><tbody>${page.rows.map(r=>`<tr data-cap-key="${escapeHtml(`${r.source_id||''}||${r.project_id||r.project_code||r.project_name||''}||${r.fiscal_year??r.budget_year??''}`)}"><td>${escapeHtml(String(r.fiscal_year??r.budget_year??'—'))}</td><td><strong>${escapeHtml(r.project_name||r.project_code||'—')}</strong><small class="cell-sub">${escapeHtml(r.project_code||'')}</small></td><td>${escapeHtml(r.category||r.asset_type||'—')}</td><td>${escapeHtml(r.location_description||r.location||'—')}</td><td>${escapeHtml(r.status||'historical source record')}<small class="cell-sub">${escapeHtml(r.source_id||'')}</small></td></tr>`).join('')}</tbody></table></div>`:emptyState('No matching capital records','Change the historical-capital filters or search.');
  return `<div class="page-stack">${domainNotice('Historical source boundary','The current capital artifact includes official historical/planned-project records. It is not the current HRM capital universe, and absence is not evidence that a project is inactive.')}<div class="metrics-grid">${metricCard('Matching records',numberFmt.format(filtered.length),'Historical/planned project records','accent')}${metricCard('Projects represented',numberFmt.format(projects),'Source identifiers/codes under current filters','neutral')}${metricCard('Source datasets',numberFmt.format(new Set(filtered.map(r=>r.source_id)).size),'Historical capital evidence layers','neutral')}${metricCard('Current-universe claim','None','Historical scope is deliberately retained','good')}</div>${panel('Historical capital project explorer','Search official project identifiers, names, locations and work descriptions. Click a row for provenance.',`<div class="local-toolbar"><label class="local-search"><span>⌕</span><input id="capital-search" value="${escapeHtml(state.capitalQuery)}" placeholder="Search project, location or work" /></label><select id="capital-year">${optionList(years,state.capitalYear,'All source years')}</select><select id="capital-source">${optionList(sources,state.capitalSource,'All sources')}</select></div>${domainPagination(filtered.length,state.capitalPage,'capital')}${table}${domainPagination(filtered.length,state.capitalPage,'capital')}`)}</div>`;
};

renderSpending=function renderSpendingIntegrated(){
  const ds=datasetStatus('spending'); if(ds.status!=='ready') return domainUnavailable('spending','Spend Explorer');
  const all=domainRows('spending');
  const types=[...new Set(all.map(r=>r.record_type).filter(Boolean))].sort(); const periods=[...new Set(all.map(r=>String(r.posting_date||'').slice(0,10)).filter(Boolean))].sort().reverse();
  const filtered=all.filter(r=>(state.spendType==='all'||r.record_type===state.spendType)&&(state.spendPeriod==='all'||String(r.posting_date||'').slice(0,10)===state.spendPeriod)&&(!state.spendQuery||normalize(`${r.business_unit||''} ${r.account||''} ${r.category||''} ${r.record_type||''}`).includes(normalize(state.spendQuery))));
  const total=filtered.reduce((sum,r)=>sum+Number(r.amount||0),0); const page=domainSlice(filtered,state.spendPage); state.spendPage=page.current;
  const table=page.rows.length?`<div class="table-wrap"><table><thead><tr><th>Report period</th><th>Summary type</th><th>Label / unit</th><th>Report context</th><th class="numeric">Published row amount</th></tr></thead><tbody>${page.rows.map(r=>`<tr data-spend-key="${escapeHtml(`${r.source_id||''}||${r.source_page||''}||${r.record_type||''}||${r.business_unit||r.account||''}||${r.amount??''}`)}"><td>${escapeHtml(String(r.posting_date||'—').slice(0,10))}</td><td>${escapeHtml(String(r.record_type||'—').replaceAll('_',' '))}</td><td>${escapeHtml(r.business_unit||r.account||'—')}</td><td>${escapeHtml(r.category||r.account||'—')}</td><td class="numeric"><strong>${money(r.amount)}</strong></td></tr>`).join('')}</tbody></table></div>`:emptyState('No matching report rows','Change the quarterly-report filters or search.');
  return `<div class="page-stack">${domainNotice('Not a transaction ledger','Spend Explorer currently contains official quarterly financial-summary table rows. These are report-level amounts, not vendor transactions or a complete accounts-payable ledger.')}<div class="metrics-grid">${metricCard('Matching report rows',numberFmt.format(filtered.length),'Quarterly financial summary rows','accent')}${metricCard('Published row amounts',compactMoney(total),'Simple sum for orientation; rows can represent different report structures','neutral')}${metricCard('Summary types',numberFmt.format(new Set(filtered.map(r=>r.record_type)).size),'Operating, capital, reserve, hospitality and related tables','neutral')}${metricCard('Transaction records','0 asserted','Transaction-level source remains a documented gap','good')}</div>${panel('Quarterly report explorer','Filter official summary-table rows. Click a row to inspect its page-level provenance.',`<div class="local-toolbar"><label class="local-search"><span>⌕</span><input id="spend-search" value="${escapeHtml(state.spendQuery)}" placeholder="Search report context or business unit" /></label><select id="spend-type">${optionList(types,state.spendType,'All summary types')}</select><select id="spend-period">${optionList(periods,state.spendPeriod,'All report periods')}</select></div>${domainPagination(filtered.length,state.spendPage,'spending')}${table}${domainPagination(filtered.length,state.spendPage,'spending')}`)}</div>`;
};

function domainUnavailable(domain,title){ const ds=datasetStatus(domain); return `<div class="page-stack">${domainNotice('Awaiting generated artifact',`${title} is not available as a validated generated dataset yet.`)}${panel(title,'Registered sources remain visible while ingestion is incomplete.',sourceCoverageList(domain))}</div>`; }
function findProc(key){ return domainRows('procurement').find(r=>`${r.source_id||''}||${r.award_id||''}||${r.vendor_name||''}||${r.awarded_date||''}`===key); }
function findCapital(key){ return domainRows('capital').find(r=>`${r.source_id||''}||${r.project_id||r.project_code||r.project_name||''}||${r.fiscal_year??r.budget_year??''}`===key); }
function findSpend(key){ return domainRows('spending').find(r=>`${r.source_id||''}||${r.source_page||''}||${r.record_type||''}||${r.business_unit||r.account||''}||${r.amount??''}`===key); }
function domainDrawer(title,eyebrow,steps,row,caveat){ const source=domainSource(row); openDrawer({title,eyebrow,html:`${evidenceSteps(steps)}${caveat?`<div class="drawer-callout"><strong>Scope boundary</strong><p>${escapeHtml(caveat)}</p></div>`:''}${source?sourceLink(source):''}`}); }

const build004Bind=bindViewEvents;
bindViewEvents=function bindDomainEvents(){
  build004Bind();
  $$('#content [data-domain-page]').forEach(btn=>btn.addEventListener('click',()=>{ const d=Number(btn.dataset.domainStep); if(btn.dataset.domainPage==='proc')state.procPage=Math.max(1,state.procPage+d); if(btn.dataset.domainPage==='capital')state.capitalPage=Math.max(1,state.capitalPage+d); if(btn.dataset.domainPage==='spending')state.spendPage=Math.max(1,state.spendPage+d); render(); }));
  const bindings=[['#proc-search','input',v=>{state.procQuery=v;state.procPage=1}],['#proc-entity','change',v=>{state.procEntity=v;state.procPage=1}],['#proc-year','change',v=>{state.procYear=v;state.procPage=1}],['#capital-search','input',v=>{state.capitalQuery=v;state.capitalPage=1}],['#capital-year','change',v=>{state.capitalYear=v;state.capitalPage=1}],['#capital-source','change',v=>{state.capitalSource=v;state.capitalPage=1}],['#spend-search','input',v=>{state.spendQuery=v;state.spendPage=1}],['#spend-type','change',v=>{state.spendType=v;state.spendPage=1}],['#spend-period','change',v=>{state.spendPeriod=v;state.spendPage=1}]];
  bindings.forEach(([selector,event,set])=>{const el=$(selector); if(el) el.addEventListener(event,e=>{set(e.target.value);render();});});
  $$('#content [data-proc-key]').forEach(el=>el.addEventListener('click',()=>{const r=findProc(el.dataset.procKey);if(r)domainDrawer(r.vendor_name||'Procurement award','PROCUREMENT EVIDENCE',[['Award date',String(r.awarded_date||'—').slice(0,10)],['Reporting entity',r.entity],['Tender / award ID',r.award_id||r.solicitation],['Published award value',money(r.original_award_value)],['Category',r.category||'—'],['Source ID',r.source_id]],r,'Public-tender award evidence is not an accounts-payable transaction and may not include later amendments or alternative procurements.');}));
  $$('#content [data-cap-key]').forEach(el=>el.addEventListener('click',()=>{const r=findCapital(el.dataset.capKey);if(r)domainDrawer(r.project_name||r.project_code||'Capital project','CAPITAL EVIDENCE',[['Project code',r.project_code||'—'],['Source year',r.fiscal_year??r.budget_year??'—'],['Category',r.category||r.asset_type||'—'],['Location',r.location_description||r.location||'—'],['Status',r.status||'historical source record'],['Source ID',r.source_id]],r,'This evidence is historical/planned-project context and must not be interpreted as the current capital universe.');}));
  $$('#content [data-spend-key]').forEach(el=>el.addEventListener('click',()=>{const r=findSpend(el.dataset.spendKey);if(r)domainDrawer(String(r.record_type||'Quarterly report row').replaceAll('_',' '),'REPORT-LEVEL SPENDING EVIDENCE',[['Report period',String(r.posting_date||'—').slice(0,10)],['Summary type',r.record_type],['Business unit / label',r.business_unit||r.account||'—'],['Published row amount',money(r.amount)],['Source page',r.source_page||'—'],['Source ID',r.source_id]],r,'This is an official quarterly financial-summary row, not a vendor transaction or complete accounts-payable ledger.');}));
};
